import {test} from 'node:test';
import assert from 'node:assert/strict';
import {parseCSV,importPlan,decodeCSV} from '../assets/finance/20261010/csv.mjs';
import * as E from '../assets/finance/20261010/engine.mjs';
import {project,carScenario} from '../assets/finance/20261010/planning.mjs';
import {FinanceDatabase} from '../server/finance-store.mjs';
import {localContext} from './finance-sqlite-adapter.mjs';
const header='ID,Note,Amount,Category,Account,Currency,Date,Event,Exclude Report\n';
const raw=header+'1,Salary,1000,Salary,Cash,IDR,01/10/2026,,False\n2,internal,-100,Outgoing transfer,Cash,IDR,02/10/2026,,True';
const config=()=>({asOf:'2026-10-10',profile:{},accounts:[{name:'Cash',balance:1000,kind:'cash',cashFlow:true,liquid:true},{name:'Deposit',balance:500,kind:'deposit',cashFlow:true,liquid:true},{name:'Stocks',balance:3000,kind:'stock',cashFlow:false,liquid:false}],liabilities:[{name:'Loan',amount:300,kind:'credit',dueDate:null,rate:0},{name:'Rent',amount:400,kind:'deferred',dueDate:null,rate:null},{name:'Office',amount:100,kind:'custody',dueDate:null,rate:null}],receivables:[],prepaids:[{name:'Rent',principal:100,start:'2026-01-01',months:3,amounts:[34,33,33],balance:33}],holdings:[{symbol:'TEST',shares:10,cost:3000,beneficiary:'personal'}],rules:[],overrides:{},budgets:[],challenges:[{month:'2026-10',bronze:900,silver:1000,gold:1100,platinum:1200}],household:{monthlyBudget:100,batamMonthlyAccrual:30,employment:[{amount:150}]},property:{value:null},btcQuantity:'0',carry:{liabilityName:'Loan',principal:300,grossRate:.06,taxRate:.2,borrowRate:0,annualFees:0},car:{price:300,downPayment:100,financing:false,operatingMonthly:1,annualInsurance:1,annualTax:1,annualMaintenance:1,minAssets:1000,minLiquidity:100,minInvestment:10,apr:0,loanMonths:12,depreciationRate:.1},retirement:{retirementMonth:'2027-10',target:10000,todayExpense:100,monthlyWithdrawal:0,oneOffWithdrawal:0,feeRate:0,returnTaxRate:0,inflation:.04,dividendYield:.04,dividendTaxRate:0,drawdownRate:0,reinvestDividends:true,contributions:[]}});
test('CSV quoted fields, delimiters, integer money, invalid dates and repeated occurrences',()=>{const p=parseCSV(header+'1,"a,b",10,Salary,Cash,IDR,10/10/2026,,False\n2,"a,b",10,Salary,Cash,IDR,10/10/2026,,False');assert.equal(p.errors.length,0);assert.equal(p.records.length,2);assert.notEqual(p.records[0].uid,p.records[1].uid);assert.equal(parseCSV(raw.replaceAll(',',';')).records.length,2);assert.equal(parseCSV(raw.replace('01/10/2026','31/02/2026')).errors.length,1);assert.equal(parseCSV(raw.replace('1000','10.5')).errors.length,1);assert.equal(decodeCSV(new TextEncoder().encode(raw)).encoding,'utf-8');});
test('Report-only replacement preserves support, is idempotent, and exposes correction candidates',()=>{const current=parseCSV(raw).records,report=header+'1,Salary,1100,Salary,Cash,IDR,01/10/2026,,False';const p=importPlan(current,parseCSV(report),{mode:'replace',preserveExcluded:true});assert.equal(p.records.length,2);assert.equal(p.correctionCandidates.length,1);assert.equal(p.counts.removed,1);assert.equal(importPlan(p.records,parseCSV(report),{mode:'replace',preserveExcluded:true}).noChange,true);assert.throws(()=>importPlan(current,parseCSV(report,{trustIds:true}),{trustIds:true}));});
test('NL excludes investments, prepaid and deferred rent; custody reduces liquidity',()=>{const p=E.position(config());assert.equal(p.nl,1100);assert.equal(p.financialLiabilities,400);assert.equal(p.bookWorth,3733);assert.equal(p.marketWorth,null);assert.equal(E.challenge(config()).current,1100);assert.equal(E.challenge(config()).final,false);});
test('Cash transfers and debt rollover never inflate accounting income or NL',()=>{const c=config(),tx=(amount,category,account='Cash')=>({uid:String(amount)+category,date:c.asOf,amount,category,account,note:'',excluded:false});const rows=E.ledger([tx(-100,'Outgoing transfer'),tx(100,'Incoming transfer','Deposit'),tx(-300,'Repayment'),tx(300,'Debt')],c);const a=E.aggregate(rows);assert.equal(a.income,0);assert.equal(a.expense,0);assert.equal(a.cashNet,0);});
test('Prepaid amortization counts expense once, excludes noncash collection and finishes at zero',()=>{const c=config();c.rules=[{category:'Rentals',kind:'accrualExpense'},{category:'Debt Collection',kind:'accrualOffset'},{category:'Loan',kind:'prepaidPayment'}];const tx=(amount,category)=>({date:c.asOf,amount,category,account:'Cash',note:''});const a=E.aggregate(E.ledger([tx(-100,'Loan'),tx(-34,'Rentals'),tx(34,'Debt Collection')],c));assert.equal(a.expense,34);assert.equal(a.cashNet,-100);assert.equal(E.amortization(c.prepaids[0]).at(-1).balance,0);});
test('Projection effective monthly compounding, tax on return, capped payment schedule',()=>{const p=config().retirement;assert.equal(project(1000000,'2026-10-10',p,.07).final,1070000);assert.equal(project(1000000,'2026-10-10',{...p,returnTaxRate:.2},.1).final,1080000);assert.equal(project(1000,'2026-10-10',{...p,cashSchedules:[{start:'2026-11',end:'2026-12',amount:100}]},0).final,800);assert.equal(project(null,'2026-10-10',p,.07).available,false);});
test('Car financing cannot improve NL by treating loan proceeds as wealth',()=>{const c=config(),market={holdings:[{symbol:'TEST',currentPrice:300}],btcIdr:1};const a=carScenario(c,market),b=carScenario(c,market,{financing:true});assert.equal(a.afterNL,800);assert.equal(a.afterNL,b.afterNL);assert.equal(b.payment,17);});
test('SQLite import preview/commit is atomic, conflict-safe and reversible without destroying archives',async()=>{
 const ctx=localContext(),seed={config:config(),active:'old',batches:[{meta:{id:'old',filename:'old.csv',coverage:{start:'2026-10-01',end:'2026-10-02'},counts:{after:2}},raw,records:parseCSV(raw).records}],snapshots:[]};const db=new FinanceDatabase(ctx,seed);await db.ready;
 const call=async(action,body)=>{const r=await db.fetch(new Request('https://private/'+action,{method:body?'POST':'GET',...(body?{headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{})}));return {status:r.status,data:await r.json()};};
 const input={revision:1,filename:'new.csv',raw:raw+'\n3,new,-20,Family,Cash,IDR,10/10/2026,,False',options:{mode:'replace'}};const preview=await call('preview',input);assert.equal(preview.data.counts.added,1);assert.equal(db.state().transactions.length,2);
 const committed=await call('import',{...input,previewToken:preview.data.previewToken});assert.equal(committed.status,200);assert.equal(db.state().transactions.length,3);assert.equal((await call('import',{...input,previewToken:preview.data.previewToken})).status,409);
 const repeat={...input,revision:2};const pp=await call('preview',repeat);assert.equal((await call('import',{...repeat,previewToken:pp.data.previewToken})).data.noChange,true);assert.equal(db.state().batches.length,2);
 assert.equal((await call('rollback',{revision:2,batchId:'old'})).status,200);assert.equal(db.state().transactions.length,2);const backup=await call('backup');assert.equal(backup.data.archives.length,2);assert.equal(backup.data.archives[0].raw,raw);
 assert.equal((await call('snapshot',{revision:3,source:'fixture',closed:true,reconciled:true})).status,400);ctx.db.close();
});

test('Preserved excluded rows cannot hide a truncated report replacement',()=>{const old=parseCSV(raw+'\n3,late,500,Salary,Cash,IDR,10/10/2026,,False').records;const partial=parseCSV(header+'1,Salary,1000,Salary,Cash,IDR,01/10/2026,,False');assert.equal(importPlan(old,partial,{mode:'replace',preserveExcluded:true}).truncated,true);});
